### ISSUE TITLE
Backend  website not opening

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [CSI-KJSCE/csi_superhero_fanpage#48]
Backend website not opening and showing error

![image](https://user-images.githubusercontent.com/83284294/147046821-d9bd5ac2-6f3c-4870-8574-6f9adc7880a0.png)

**Comment by KrutikaBhatt** [comment]
The Backend website is just a node server deployed to read and manage the data provided in json files by the participants. There was an error caused by some code modifications for a while in the backend. It is restored and live up.

Anyways, it is just used as a representative purpose on how backend fetches data in json format and while accessing you can view all the data.It was supposed to be for beginner level coders only.
